name: Check conditions
on: 
  workflow_dispatch:
    inputs:
      job1_input:
        type: boolean
        description: 'Select to deploy job one'
        required: true
      job2_input:
        type: boolean
        description: 'Select to deploy job two'
        required: true
      job3_input:
        type: boolean
        description: 'Select to deploy job three'
        required: true
jobs:
  job_one:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job1_input == 'true' }}
    steps:
      - name: print job1 output 
        run: |-
          echo "Hey, this is job1 output"
  job_two:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job2_input == 'true' }}
    steps:
      - name: print job2 output 
        run: |-
          echso "Hey, this is job2 output"
  job_three:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job3_input == 'true' }}
    steps:
      - name: print job3 output 
        run: |-
          echo "Hey, this is job3 output"
  test_passed:
    runs-on: ubuntu-latest
    if: always()
    needs: [job_one, job_two, job_three]
    outputs:
      all_jobs_output: ${{ steps.set_passed_output.outputs.passed }}
    steps:
      - name: Check job1 status
        if: ${{ needs.job_one.result != 'success' && github.event.inputs.job1_input == 'true' }}
        run: exit 1

      - name: Check job2 status
        if: ${{ needs.job_two.result != 'success' && github.event.inputs.job2_input == 'true' }}
        run: exit 1

      - name: Check job3 status
        if: ${{ needs.job_three.result != 'success' && github.event.inputs.job3_input == 'true' }}
        run: exit 1

      - name: Set passed output
        id: set_passed_output
        run: echo "passed=true" >> $GITHUB_OUTPUT
          
  depend_job_one:
    runs-on: ubuntu-latest
    needs: test_passed
    steps:
      - name: print job1 output 
        run: |-
          echo "Hey, this is job1 output"
          
  depend_job_two:
    runs-on: ubuntu-latest
    needs: test_passed
    steps:
      - name: print job2 output 
        run: |-
          echo "Hey, this is job2 output"
 
  depend_job_three:
    runs-on: ubuntu-latest
    needs: test_passed
    steps:
      - name: print job3 output 
        run: |-
          echo "Hey, this is job3 output"
