name: git checkout test

on: 
  push:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Provide commit sha to rollback'
        required: true
        type: string
        default: ''
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout_job
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}
          
      - name: Get branch name
        id: get_branch_name
        run: echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      
      - name: check git log 
        run: |-
          git branch
          git log
    
