name: checkbox
on:
  push:
  workflow_dispatch:
    inputs:
      checkbox:
        type: boolean
        description: 'Select to run job'
        required: true
jobs:
  first_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.checkbox == 'true' }}
    steps:
        - name: print output job1
          run: echo "Hello, this job has been executed"
    
  second_job:
    runs-on: ubuntu:latest
    if: ${{ github.event.inputs.checkbox != 'true' }}
    steps:
      - name: print output job2
        run: echo "Hello, this job has been executed"
