name: Check conditions
on: 
  workflow_dispatch:
    inputs:
      job1_input:
        type: boolean
        description: 'Select to deploy job one'
        required: true
      job2_input:
        type: boolean
        description: 'Select to deploy job two'
        required: true
      job3_input:
        type: boolean
        description: 'Select to deploy job three'
        required: true
jobs:
  job_one:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job1_input == 'true' }}
    steps:
      - name: print job1 output 
        run: |-
          echo "Hey, this is job1 output"
  job_two:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job2_input == 'true' }}
    steps:
      - name: print job2 output 
        run: |-
          echso "Hey, this is job2 output"
  job_three:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job3_input == 'true' }}
    steps:
      - name: print job3 output 
        run: |-
          echo "Hey, this is job3 output"
          
  depend_job_one:
    runs-on: ubuntu-latest
    needs: job_one
    if: ${{ github.event.inputs.job1_input == 'true' }}
    steps:
      - name: print job1 output 
        run: |-
          echo "Hey, this is job1 output"
          
#   depend_job_two:
#     runs-on: ubuntu-latest
#     needs: job_two
#     if: ${{ github.event.inputs.job2_input == 'true' }}
#     steps:
#       - name: print job2 output 
#         run: |-
#           echo "Hey, this is job2 output"
          
  depend_job_two_one_more:
    runs-on: ubuntu-latest
    needs: job_two
    if: ${{ needs.job_two.result == 'success' }}
    steps:
      - name: print job2 output 
        run: |-
          echo "Hey, this is job2 output"
  
          
  depend_job_three:
    runs-on: ubuntu-latest
    needs: job_three
    if: ${{ github.event.inputs.job3_input == 'true' }}
    steps:
      - name: print job3 output 
        run: |-
          echo "Hey, this is job3 output"
