name: inputs testing

on: 
  workflow_dispatch:
    inputs:
      commit_sha:
          description: 'provide the last commit sha to rollback'
          required: true 
          type: string
          default: ''
      skip_job:
        description: 'Enter value to skip the tests'
        required: false
        type: string
        default: ''
      multi_choice:
        description: 'enter the things'
        required: false
        default: 'warning' 
        type: choice
        options:
        - one
        - two
        - three
      checkbox:
        type: boolean
        description: 'Select to deploy job'
        required: true
      multi-choice:
        type: multi-choice
        description: select packages
        options: 
        - go-service1
        - go-service2
        - py-service1
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.skip_job == '' }}
    steps:
      - name: first step
        run: echo ${{ github.event.inputs.commit_sha }}
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo ${{ github.event.inputs.commit_sha }}
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: |-
          echo "IMAGE_TAG=$(echo ${{ github.event.inputs.commit_sha }})"
          echo "$IMAGE_TAG"
          echo $COMMIT_SHA
  job4:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.checkbox == 'true' }}
    steps:
      - name: first step
        run: |-
          echo "IMAGE_TAG=$(echo ${{ github.event.inputs.commit_sha }})"
          echo "$IMAGE_TAG"
          echo $COMMIT_SHA
  job5:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: |-
          echo ${{ github.event.inputs.multi-choice }}
  job6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         fetch-depth: 10
         ref: ${{ github.event.inputs.commit_sha }}
      - name: print commit sha
        run: |-
          echo ${GITHUB_SHA}
          echo ${GITHUB_REF#refs/heads/}
      
  

