name: manual testing

on: 
  workflow_dispatch:
    inputs:
       commit_sha:
          description: 'provide the last commit sha to rollback'
          required: true 
          type: string
          default: ''
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo ${{ github.event.inputs.commit_sha }}
  

