name: output test

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Provide commit sha'
        required: true
        type: string
        default: ''

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.output1.outputs.test }}
      output2: ${{ steps.output2.outputs.test }}
    steps:
      - id: output1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: output2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
