name: testing the env variables

on:
#   push:
#     branches:
#       - '**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  testing_variables:
    runs-on: ubuntu-latest
    steps:
     - name: add data
       run: echo "Hello hari" >> $GITHUB_ENV
     - name: print GITHUB_ENV
       run: echo $GITHUB_ENV >> hari.txt
       
     - name: cat file
       run: cat hari.txt
